# Generated by Django 5.1.4 on 2024-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('content', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
