# Generated by Django 5.1.4 on 2024-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_travelnews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnews',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
