# Generated by Django 5.1.4 on 2024-12-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_travelnews_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelnews',
            options={},
        ),
    ]
