# Generated by Django 5.1.4 on 2024-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_travelnews_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnews',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
