# Generated by Django 5.1.4 on 2024-12-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_travelnews_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelnews',
            name='read_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
