# Generated by Django 5.1.4 on 2024-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_travelnews_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelnews',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
