# Generated by Django 5.1.4 on 2024-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='persons',
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
