# Generated by Django 5.1.4 on 2024-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_booking_category_remove_booking_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('Online', 'Online'), ('On Site', 'On Site')], default='None', max_length=50),
        ),
    ]
